merge_queue:
  max_parallel_checks: 1

queue_rules:
  - name: default
    merge_method: squash
    update_method: merge
    batch_size: 1
    queue_conditions:
      - "#approved-reviews-by >= 1"
      - base = main
      - -draft
      - -conflict
      - "check-success = test"
      - "check-success = lint"
      - "check-success = build"
      - "check-success = e2e"
